# Use postgres/example user/password credentials
version: '3.1'

services:
  postgresDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pgdb
    volumes:
      - /var/lib/postgres/data
    ports:
      - "5432:5432"

  template-api-first:
    build: .
    container_name: template-api-first
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/pgdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true

